---
title: "cross validation results BRCA"
author: "Ente Kang"
date: "`r Sys.Date()`"
output: word_document
---

# 10 fold cross validation

# BRCA COX PH 
```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(survival)
library(comprehenr)
library(quantreg)
brca <- readxl::read_excel("C:/Users/kange/Desktop/Thesis/data/BRCAdataset_fullcov.xlsx")
brca1 <- brca[complete.cases(brca[, c("LengthofSurgery_hour", "CA_125BeforeOR_div100")]),]
brca1 <- brca1[, -c(1, 4:5)]

cv_conc <- rep(0, 100)
for (k in 1:100){
  splits <- split(brca1, sample(1:10, nrow(brca1), replace = T))
  
  c <- rep(0, 10)
  for (i in 1:10){
    d_minusi <- bind_rows(splits[-c(i)])  # dataset without ith fold 
    fit <- coxph(Surv(pfs_time, pfs_out) ~BRCA_Overall2 + LengthofSurgery_hour+ADJcycles+Ascites+DSscore, 
                 data = d_minusi) # fit the "training model" 
    
    # predict new data's HR/risk using training model
    preds <- predict(fit, newdata = splits[[i]])
    
    # bind preds to testing data
    test <- splits[[i]]
    test_preds <- cbind(test, preds)
    
    # useful info
    surv_time <- test$pfs_time
    censor_status <- test$pfs_out
    risk <- test_preds$preds
    
    # call concordance
    
    good_pairs <- to_vec(for(i in 1:nrow(test)) for(j in 1:nrow(test)) if ( !( (surv_time[i]<surv_time[j]) & (censor_status[i]==0) | 
                                                                               (censor_status[i]==0) & (censor_status[j]==0) ) ) c(i,j))
    
    obs1 <- good_pairs[seq(1, length(good_pairs), by = 2)]
    obs2 <- good_pairs[seq(2, length(good_pairs), by = 2)]
    time1 <- surv_time[obs1]
    time2 <- surv_time[obs2]
    status1 <- censor_status[obs1]
    status2 <- censor_status[obs2]
    risk1 <- risk[obs1]
    risk2 <- risk[obs2]
    good_df <- data.frame(cbind(obs1, obs2, time1, time2, status1, status2, risk1, risk2))
    good_df <- good_df %>% filter(obs1 != obs2) # remove pairs where obs1=obs2
    
    good_df <- good_df %>% mutate(conc = ifelse((time1!=time2 & time1>time2 & risk1<risk2) | (time1==time2 & status1!=0 & status2!=0 & risk1==risk2) |
                                                  (status1==0 & status2!=0 & risk1<risk2), 1, 0.5))
    concordance <- mean(good_df$conc)
    c[i] <- concordance
    
  }
  cross_val_score <- mean(c)
  cv_conc[k] <- cross_val_score
}
mean(cv_conc)
```

# BRCA COX PH - W/ OSD
```{r, echo=FALSE}
osd_outliers <- c(143, 14, 95, 6, 203, 24, 39, 27, 20, 35, 47, 17, 63)
brcaosd <- brca1[-osd_outliers, ]

cv_conc <- rep(0, 100)
for (k in 1:100){
  splits <- split(brcaosd, sample(1:10, nrow(brcaosd), replace = T))
  
  c <- rep(0, 10)
  for (i in 1:10){
    d_minusi <- bind_rows(splits[-c(i)])  # dataset without ith fold 
    fit <- coxph(Surv(pfs_time, pfs_out) ~BRCA_Overall2 + LengthofSurgery_hour+ADJcycles+Ascites+DSscore, 
                 data = d_minusi) # fit the "training model" 
    
    # predict new data's HR/risk using training model
    preds <- predict(fit, newdata = splits[[i]])
    
    # bind preds to testing data
    test <- splits[[i]]
    test_preds <- cbind(test, preds)
    
    # useful info
    surv_time <- test$pfs_time
    censor_status <- test$pfs_out
    risk <- test_preds$preds
    
    # call concordance
    
    good_pairs <- to_vec(for(i in 1:nrow(test)) for(j in 1:nrow(test)) if ( !( (surv_time[i]<surv_time[j]) & (censor_status[i]==0) | 
                                                                               (censor_status[i]==0) & (censor_status[j]==0) ) ) c(i,j))
    
    obs1 <- good_pairs[seq(1, length(good_pairs), by = 2)]
    obs2 <- good_pairs[seq(2, length(good_pairs), by = 2)]
    time1 <- surv_time[obs1]
    time2 <- surv_time[obs2]
    status1 <- censor_status[obs1]
    status2 <- censor_status[obs2]
    risk1 <- risk[obs1]
    risk2 <- risk[obs2]
    good_df <- data.frame(cbind(obs1, obs2, time1, time2, status1, status2, risk1, risk2))
    good_df <- good_df %>% filter(obs1 != obs2) # remove pairs where obs1=obs2
    
    good_df <- good_df %>% mutate(conc = ifelse((time1!=time2 & time1>time2 & risk1<risk2) | (time1==time2 & status1!=0 & status2!=0 & risk1==risk2) |
                                                  (status1==0 & status2!=0 & risk1<risk2), 1, 0.5))
    concordance <- mean(good_df$conc)
    c[i] <- concordance
    
  }
  cross_val_score <- mean(c)
  cv_conc[k] <- cross_val_score
}
mean(cv_conc)

```

# BRCA COX PH - W/ DEVIANCE
```{r, echo=FALSE}
dev_outliers <- c(27,21,143,14,24,109,7,67,63,153,142,228,39)
brcadev <- brca1[-dev_outliers,]

cv_conc <- rep(0, 100)
for (k in 1:100){
  splits <- split(brcadev, sample(1:10, nrow(brcadev), replace = T))
  
  c <- rep(0, 10)
  for (i in 1:10){
    d_minusi <- bind_rows(splits[-c(i)])  # dataset without ith fold 
    fit <- coxph(Surv(pfs_time, pfs_out) ~BRCA_Overall2 + LengthofSurgery_hour+ADJcycles+Ascites+DSscore, 
                 data = d_minusi) # fit the "training model" 
    
    # predict new data's HR/risk using training model
    preds <- predict(fit, newdata = splits[[i]])
    
    # bind preds to testing data
    test <- splits[[i]]
    test_preds <- cbind(test, preds)
    
    # useful info
    surv_time <- test$pfs_time
    censor_status <- test$pfs_out
    risk <- test_preds$preds
    
    # call concordance
    
    good_pairs <- to_vec(for(i in 1:nrow(test)) for(j in 1:nrow(test)) if ( !( (surv_time[i]<surv_time[j]) & (censor_status[i]==0) | 
                                                                               (censor_status[i]==0) & (censor_status[j]==0) ) ) c(i,j))
    
    obs1 <- good_pairs[seq(1, length(good_pairs), by = 2)]
    obs2 <- good_pairs[seq(2, length(good_pairs), by = 2)]
    time1 <- surv_time[obs1]
    time2 <- surv_time[obs2]
    status1 <- censor_status[obs1]
    status2 <- censor_status[obs2]
    risk1 <- risk[obs1]
    risk2 <- risk[obs2]
    good_df <- data.frame(cbind(obs1, obs2, time1, time2, status1, status2, risk1, risk2))
    good_df <- good_df %>% filter(obs1 != obs2) # remove pairs where obs1=obs2
    
    good_df <- good_df %>% mutate(conc = ifelse((time1!=time2 & time1>time2 & risk1<risk2) | (time1==time2 & status1!=0 & status2!=0 & risk1==risk2) |
                                                  (status1==0 & status2!=0 & risk1<risk2), 1, 0.5))
    concordance <- mean(good_df$conc)
    c[i] <- concordance
    
  }
  cross_val_score <- mean(c)
  cv_conc[k] <- cross_val_score
}
mean(cv_conc)
```

# CQR 0.1

```{r, echo=FALSE}

cv_conc <- rep(0, 100)
for (k in 1:100){
  splits <- split(brca1, sample(1:10, nrow(brca1), replace = T))

c <- rep(0, 10)
for (i in 1:10){
  d_minusi <- bind_rows(splits[-c(i)])  # dataset without ith fold 
  fit <- crq(Surv(pfs_time, pfs_out) ~BRCA_Overall2 + LengthofSurgery_hour+ADJcycles+Ascites+DSscore, 
               data = d_minusi, method = "PengHuang")    # fit the "training model" 
  
  # predict new data's risk/time using training model
  q1coef <- coef(fit, taus = c(0.1))
  #model matrix for data to be predicted, splits[[i]]
  somedf <- splits[[i]] %>% mutate(BRCA_Overall2Positive = ifelse(BRCA_Overall2=="Positive", 1, 0), 
                    AscitesYes = ifelse(Ascites=="Yes", 1, 0), DSscoreLow = ifelse(DSscore=="Low", 1, 0), 
                    DSscoreModerate=ifelse(DSscore=="Moderate", 1, 0))
  somedf <- somedf %>% select(c(BRCA_Overall2Positive, LengthofSurgery_hour, ADJcycles, 
                                AscitesYes, DSscoreLow, DSscoreModerate))
  int <- rep(1, nrow(splits[[i]]))
  modelmatrix <- cbind(int, somedf)
  preds1 <- data.frame(preds=as.matrix(modelmatrix) %*% q1coef)
  
  # bind preds to testing data
  test <- splits[[i]]
  test_preds <- cbind(test, preds1)
  
  # useful info
  surv_time <- test$pfs_time
  censor_status <- test$pfs_out
  risk <- test_preds$preds
  
  # call concordance
  
  good_pairs <- to_vec(for(i in 1:nrow(test)) for(j in 1:nrow(test)) if ( !( (surv_time[i]<surv_time[j]) & (censor_status[i]==0) | 
                                                                             (censor_status[i]==0) & (censor_status[j]==0) ) ) c(i,j))
  
  obs1 <- good_pairs[seq(1, length(good_pairs), by = 2)]
  obs2 <- good_pairs[seq(2, length(good_pairs), by = 2)]
  time1 <- surv_time[obs1]
  time2 <- surv_time[obs2]
  status1 <- censor_status[obs1]
  status2 <- censor_status[obs2]
  risk1 <- risk[obs1]
  risk2 <- risk[obs2]
  good_df <- data.frame(cbind(obs1, obs2, time1, time2, status1, status2, risk1, risk2))
  good_df <- good_df %>% filter(obs1 != obs2) # remove pairs where obs1=obs2
  
  # need to reverse direction of risk1, risk2 since 'risk' here refers to pred. survival vs coxph=hazard
  
  good_df <- good_df %>% mutate(conc = ifelse((time1!=time2 & time1>time2 & risk1>risk2) | (time1==time2 & status1!=0 & status2!=0 & risk1==risk2) |
                                                (status1==0 & status2!=0 & risk1>risk2), 1, 0.5))
  concordance <- mean(good_df$conc)
  c[i] <- concordance
  
}
cross_val_score <- mean(c)
cv_conc[k] <- cross_val_score
}
mean(cv_conc)
```


# CQR 0.2
```{r, echo=FALSE}
cv_conc <- rep(0, 100)
for (k in 1:100){
  splits <- split(brca1, sample(1:10, nrow(brca1), replace = T))

  c <- rep(0, 10)
  for (i in 1:10){
    d_minusi <- bind_rows(splits[-c(i)])  # dataset without ith fold 
    fit <- crq(Surv(pfs_time, pfs_out) ~BRCA_Overall2 + LengthofSurgery_hour+ADJcycles+Ascites+DSscore, 
               data = d_minusi, method = "PengHuang")    # fit the "training model" 
  
  # predict new data's risk/time using training model
    q1coef <- coef(fit, taus = c(0.2))
  #model matrix for data to be predicted, splits[[i]]
    somedf <- splits[[i]] %>% mutate(BRCA_Overall2Positive = ifelse(BRCA_Overall2=="Positive", 1, 0), 
                    AscitesYes = ifelse(Ascites=="Yes", 1, 0), DSscoreLow = ifelse(DSscore=="Low", 1, 0), 
                    DSscoreModerate=ifelse(DSscore=="Moderate", 1, 0))
    somedf <- somedf %>% select(c(BRCA_Overall2Positive, LengthofSurgery_hour, ADJcycles, 
                                AscitesYes, DSscoreLow, DSscoreModerate))
    int <- rep(1, nrow(splits[[i]]))
    modelmatrix <- cbind(int, somedf)
    preds1 <- data.frame(preds=as.matrix(modelmatrix) %*% q1coef)
  
  # bind preds to testing data
    test <- splits[[i]]
    test_preds <- cbind(test, preds1)
  
  # useful info
    surv_time <- test$pfs_time
    censor_status <- test$pfs_out
    risk <- test_preds$preds
  
  # call concordance
  
    good_pairs <- to_vec(for(i in 1:nrow(test)) for(j in 1:nrow(test)) if ( !( (surv_time[i]<surv_time[j]) & (censor_status[i]==0) | 
                                                                             (censor_status[i]==0) & (censor_status[j]==0) ) ) c(i,j))
  
    obs1 <- good_pairs[seq(1, length(good_pairs), by = 2)]
    obs2 <- good_pairs[seq(2, length(good_pairs), by = 2)]
    time1 <- surv_time[obs1]
    time2 <- surv_time[obs2]
    status1 <- censor_status[obs1]
    status2 <- censor_status[obs2]
    risk1 <- risk[obs1]
    risk2 <- risk[obs2]
    good_df <- data.frame(cbind(obs1, obs2, time1, time2, status1, status2, risk1, risk2))
    good_df <- good_df %>% filter(obs1 != obs2) # remove pairs where obs1=obs2
  
  # need to reverse direction of risk1, risk2 since 'risk' here refers to pred. survival vs coxph=hazard
  
    good_df <- good_df %>% mutate(conc = ifelse((time1!=time2 & time1>time2 & risk1>risk2) | (time1==time2 & status1!=0 & status2!=0 & risk1==risk2) |
                                                (status1==0 & status2!=0 & risk1>risk2), 1, 0.5))
    concordance <- mean(good_df$conc)
    c[i] <- concordance
    try(if(is.na(concordance)) stop("na found"))
  
  }
  cross_val_score <- mean(c)
  cv_conc[k] <- cross_val_score
}
mean(cv_conc)
```

# CQR 0.4
```{r, echo=FALSE}
cv_conc <- rep(0, 100)
for (k in 1:100){
  splits <- split(brca1, sample(1:10, nrow(brca1), replace = T))

c <- rep(0, 10)
for (i in 1:10){
  d_minusi <- bind_rows(splits[-c(i)])  # dataset without ith fold 
  fit <- crq(Surv(pfs_time, pfs_out) ~BRCA_Overall2 + LengthofSurgery_hour+ADJcycles+Ascites+DSscore, 
               data = d_minusi, method = "PengHuang")    # fit the "training model" 
  
  # predict new data's risk/time using training model
  q1coef <- coef(fit, taus = c(0.4))
  #model matrix for data to be predicted, splits[[i]]
  somedf <- splits[[i]] %>% mutate(BRCA_Overall2Positive = ifelse(BRCA_Overall2=="Positive", 1, 0), 
                    AscitesYes = ifelse(Ascites=="Yes", 1, 0), DSscoreLow = ifelse(DSscore=="Low", 1, 0), 
                    DSscoreModerate=ifelse(DSscore=="Moderate", 1, 0))
  somedf <- somedf %>% select(c(BRCA_Overall2Positive, LengthofSurgery_hour, ADJcycles, 
                                AscitesYes, DSscoreLow, DSscoreModerate))
  int <- rep(1, nrow(splits[[i]]))
  modelmatrix <- cbind(int, somedf)
  preds1 <- data.frame(preds=as.matrix(modelmatrix) %*% q1coef)
  
  # bind preds to testing data
  test <- splits[[i]]
  test_preds <- cbind(test, preds1)
  
  # useful info
  surv_time <- test$pfs_time
  censor_status <- test$pfs_out
  risk <- test_preds$preds
  
  # call concordance
  
  good_pairs <- to_vec(for(i in 1:nrow(test)) for(j in 1:nrow(test)) if ( !( (surv_time[i]<surv_time[j]) & (censor_status[i]==0) | 
                                                                             (censor_status[i]==0) & (censor_status[j]==0) ) ) c(i,j))
  
  obs1 <- good_pairs[seq(1, length(good_pairs), by = 2)]
  obs2 <- good_pairs[seq(2, length(good_pairs), by = 2)]
  time1 <- surv_time[obs1]
  time2 <- surv_time[obs2]
  status1 <- censor_status[obs1]
  status2 <- censor_status[obs2]
  risk1 <- risk[obs1]
  risk2 <- risk[obs2]
  good_df <- data.frame(cbind(obs1, obs2, time1, time2, status1, status2, risk1, risk2))
  good_df <- good_df %>% filter(obs1 != obs2) # remove pairs where obs1=obs2
  
  # need to reverse direction of risk1, risk2 since 'risk' here refers to pred. survival vs coxph=hazard
  
  good_df <- good_df %>% mutate(conc = ifelse((time1!=time2 & time1>time2 & risk1>risk2) | (time1==time2 & status1!=0 & status2!=0 & risk1==risk2) |
                                                (status1==0 & status2!=0 & risk1>risk2), 1, 0.5))
  concordance <- mean(good_df$conc)
  c[i] <- concordance
  if (is.na(concordance)) break
}
cross_val_score <- mean(c)
cv_conc[k] <- cross_val_score
if (anyNA(cv_conc)) break
}
mean(cv_conc)
```

